import BlogNavbar from '../../components/BlogNavbar' 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
        <div className='w-full bg-slate-200'>
            <BlogNavbar/>
          {children}
        </div>
    

  );
}
