import TourNavbar from '../../components/TourNavbar' 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
        <div className='w-full h-full bg-slate-200 overflow-y-auto'>
            <TourNavbar/>
          {children}
        </div>
    

  );
}
