// app/layout.js

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/** Conditionally render Navbar only if authenticated */}
        <Navbar />
        {children}
        <Script src="https://media-library.cloudinary.com/global/all.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
