// app/layout.js

import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../contexts/AuthContext";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {/** Conditionally render Navbar only if authenticated */}
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
